players_pieces_map = {
            'pawn1': 'pawn',
            'pawn2': 'pawn',
            'pawn3': 'pawn',
            'pawn4': 'pawn',
            'pawn5': 'pawn',
            'pawn6': 'pawn',
            'pawn7': 'pawn',
            'pawn8': 'pawn',
            'rook1': 'rook',
            'rook2': 'rook',
            'knight1': 'knight',
            'knight2': 'knight',
            'bishop1': 'bishop',
            'bishop2': 'bishop',
            'king': 'king',
            'queen': 'queen',
        }

players_pieces_location_map = {
            'pawn1': '1',
            'pawn2': '2',
            'pawn3': '3',
            'pawn4': '4',
            'pawn5': '5',
            'pawn6': '6',
            'pawn7': '7',
            'pawn8': '8',
            'rook1': '1',
            'rook2': '8',
            'knight1': '2',
            'knight2': '7',
            'bishop1': '3',
            'bishop2': '6',
            'king': '4',
            'queen': '5',
        }